config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :shops do
    resources :reviews, except:[:show, :index]
  end

root "shops#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :shops
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :photo, :styles=> {:small=> "350x350"}

  do_not_validate_attachment_file_type :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shops
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_shop
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id=current_user.id
    @review.shop_id=@shop.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @shop, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action  :authenticate_user!, except: [:index, :show]

  # GET /shops
  # GET /shops.json
  def index
    if params[:category].blank?
    @shops = Shop.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @shops = Shop.where(category_id: @category_id).order("created_at DESC")
      end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @reviews = Review.where(shop_id: @shop.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /shops/new
  def new
    @shop = current_user.shops.build
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = current_user.shops.build(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :owner, :description, :location, :contact, :photo, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BizMart" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= shops_path %>>BizMart</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>



    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Categories</h3>
            <ul class="nav nav-list">
              <% Category.all.each do |category| %>
                  <li><%= link_to category.name, shops_path(category: category.name) %></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@shop, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
    $('#star-rating').raty({
        path: '/assets',
        scoreName: 'review[rating'
    });
</script>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>


<%= link_to 'Back', shop_path(@shop) %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_path(@shop) %>

app/views/shops/_form.html.erb
<%= form_for @shop, :html => { :class => "form-horizontal shop" } do |f| %>

    <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <%= f. label :category%>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"} %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@shop[:name]) %>
  </div><br>
    <p>
      <%= f.file_field :photo %>
    </p>
  <div class="control-group">
    <%= f.label :owner, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :owner, :class => 'form-control' %>
    </div>
    <%= error_span(@shop[:owner]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@shop[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%= error_span(@shop[:location]) %>
  </div>
  <div class="control-group">
    <%= f.label :contact, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contact, :class => 'form-control' %>
    </div>
    <%= error_span(@shop[:contact]) %>
  </div>



  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            shops_path, :class => 'btn btn-default' %>

<% end %>

app/views/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/index.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

    <% @shops.each do |shop| %>

        <h1><%= link_to shop.name, shop %></h1><br>
        <%= if shop.photo?
              image_tag shop.photo.url(:small), :class => "img-thumbnail"
            else
              image_tag("avatar.png", id: "img_prev", alt: "no image",:class => "img-thumbnail")
            end %>
        <!--<%= shop.owner %>
        <%= shop.description %>
        <%= shop.location %>
        <%= shop.contact %>-->

    <hr>
    <% end %>

<br>
<br>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shop_path,
            :class => 'btn btn-primary' %>

app/views/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @shop.name %></dd>
  <p>
    <%= if @shop.photo?
          image_tag(@shop.photo , :class => "img-thumbnail")
        else
          image_tag("avatar.png", id: "img_prev", alt: "no image",:class => "img-thumbnail")
        end %>
  </p>
  <div class="star-rating" data-score= <%= @avg_review %> ></div>
  <em><%= "#{@reviews.length} reviews" %></em><br>
  <dt><strong><%= model_class.human_attribute_name(:owner) %>:</strong></dt>
  <dd><%= @shop.owner %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @shop.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @shop.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @shop.contact %></dd>
</dl>

<br>
<br>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shops_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shop_path(@shop), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shop_path(@shop),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<br>
<br>
<br>
<div>
  <h3>Customer Reviews</h3>
  <!--<h1 class="review_title"><%= @shop.name %></h1>-->
  <!--<p><%= @shop.description %></p>-->

  <% if @reviews.blank? %>
      <h3>No reviews yet. Have you used their services? Be the first to write a review</h3>
      <%= link_to "Write a Review", new_shop_review_path(@shop), class: "btn btn-danger" %>
  <% else %>
      <% @reviews.each do |review| %>
          <div class="reviews">
            <div class="star-rating" data-score= <%= review.rating %> ></div>
            <p><%= review.comment %></p>
          </div>
      <% end %>
  <% end %>
</div>
<%= link_to "Write a Review", new_shop_review_path(@shop), class: "btn btn-danger" %>

<script>
    $('.star-rating').raty({
        path: '/assets',
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        }
    });
</script>